### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by axxg** [pklaus/brother_ql#10] opened 2016-12-02 18:30 UTC
Hi,
nice script, but i have a problem at a raspberry pi 3 with raspbian:
the log:

    copying lib/matplotlib/tests/baseline_images/test_axes/pcolormesh.png -> build/lib.linux-armv7l-2.7/matplotlib/tests/baseline_images/test_axes

    [...]

    In file included from src/ft2font.cpp:9:0:

    src/mplutils.h:31:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden

     #include <Python.h>

                    ^

    compilation terminated.

    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
    Cleaning up...
    Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z9mhMv/matplotlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-D6YooL-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-Z9mhMv/matplotlib
    Storing debug log for failure in /root/.pip/pip.log
    pi@raspberrypi:~/Downloads $

**Comment by pklaus** [comment] 2016-12-10 08:08
Hi @axxg, thanks for the report. (I allowed myself to shorten the error output to the relevant lines.)

**In short: This is fixed in the commit c18c3f6 by removing the dependency on the package matplotlib.**

Details:
The problem is that you are missing the python-dev package on your Raspberry Pi. This means that the installation of the matplotlib package (a dependency of this software at the time) was failing. Actually, I don't use this package anymore in brother_ql and thus I kicked out that requirement. I should have done that earlier. I also removed another nasty dependency, numpy in the commit 17274a8. It's a pretty standard package but the installation from sources (done by the `pip install ...` command) takes a while on the Raspberry Pi and I was not using the package heavily.

So thanks for reporting. And please check again, if it works for you now.

**Comment by pklaus** [comment] 2016-12-15 19:51
I'm closing this now. Let me know if you are still having problems.

**Closed by pklaus** 2016-12-15 19:51 UTC
